const fullMoviesDescriptions = [
  {
    id: 1,
    name: `Movie title 1`,
    posterImage: `poster_image1`,
    previewImage: `mpreview_image1`,
    backgroundImage: `background_image1`,
    backgroundColor: `#960e29`,
    description: `Movie description 1`,
    rating: 9.9,
    scoresCount: 1000,
    director: `Director 1`,
    starring: [`Awesome Actor`, `Awesome Actress`],
    runTime: 122,
    genre: `Comedy`,
    released: 2000,
    isFavorite: true,
    videoSrc: `video_link`,
    videoPreviewSrc: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  },
  {
    id: 2,
    name: `Movie title 2`,
    posterImage: `poster_image2`,
    previewImage: `mpreview_image2`,
    backgroundImage: `background_image2`,
    backgroundColor: `#960e29`,
    description: `Movie description 2`,
    rating: 9.9,
    scoresCount: 1000,
    director: `Director 2`,
    starring: [`Awesome Actor`, `Awesome Actress`],
    runTime: 122,
    genre: `Comedy`,
    released: 2002,
    isFavorite: true,
    videoSrc: `video_link`,
    videoPreviewSrc: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  },
  {
    id: 3,
    name: `Movie title 3`,
    posterImage: `poster_image3`,
    previewImage: `mpreview_image3`,
    backgroundImage: `background_image3`,
    backgroundColor: `#960e29`,
    description: `Movie description 3`,
    rating: 9.9,
    scoresCount: 1000,
    director: `Director 3`,
    starring: [`Awesome Actor`, `Awesome Actress`],
    runTime: 122,
    genre: `Comedy`,
    released: 2003,
    isFavorite: true,
    videoSrc: `video_link`,
    videoPreviewSrc: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  },
  {
    id: 4,
    name: `Movie title 4`,
    posterImage: `poster_image4`,
    previewImage: `mpreview_image4`,
    backgroundImage: `background_image4`,
    backgroundColor: `#960e29`,
    description: `Movie description 4`,
    rating: 9.9,
    scoresCount: 1000,
    director: `Director 3`,
    starring: [`Awesome Actor`, `Awesome Actress`],
    runTime: 122,
    genre: `Comedy`,
    released: 2000,
    isFavorite: true,
    videoSrc: `video_link`,
    videoPreviewSrc: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  },
];

const fullMovieDescription = fullMoviesDescriptions[0];

const moviesFromServer = [{
  id: 1,
  name: `Movie title`,
  poster_image: `img/poster.jpg`,
  preview_image: `img/preview.jpg`,
  background_image: `img/bg.jpg`,
  background_color: `#ffffff`,
  video_link: `https://some-link`,
  preview_video_link: `https://some-link`,
  description: `Description`,
  rating: 8.9,
  scores_count: 100,
  director: `Director`,
  starring: [`Awesome Actor`, `Awesome Actress`],
  run_time: 99,
  genre: `Comedy`,
  released: 2014,
  is_favorite: false
}];


export {
  fullMoviesDescriptions,
  fullMovieDescription,
  moviesFromServer
};
